security:
    encoders:
        App\Entity\User:
            algorithm: auto
        md5:
            algorithm: md5

    providers:
        users:
            entity:
                class: 'App\Entity\User'
                property: 'username'
    firewalls:
        main:
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /admin
                remember_me_parameter: 'login[remember_me]'
            access_denied_handler: App\Security\Authorization\AccessDeniedHandler
            anonymous: true
            provider: users
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_admin_logout
                target: app_admin_login
            switch_user: { parameter: switch }

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
