version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx-proxy/cert/:/etc/nginx/certs/
    networks:
      - web

  nginx:
    image: nginx:1.21
    restart: on-failure
    volumes:
      - .:/home/app
      - ./docker/nginx/conf/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
    networks:
      - web

  php:
    build: docker/php
    restart: on-failure
    working_dir: /home/app
    volumes:
      - .:/home/app:cached
      - appdata:/home/app/var/cache
      - appdata:/home/app/var/log
      - ./vendor:/home/app/vendor:delegated
    networks:
      - web

  db:
    image: mariadb:10.6
    restart: on-failure
    volumes:
      - .:/home/app
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - web

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - web

  redis:
    image: redis:6.2-alpine
    networks:
      - web

  smtp:
    image: schickling/mailcatcher
    environment:
      VIRTUAL_PORT: 1080
    networks:
      - web

  selenium:
    image: selenium/standalone-chrome-debug:3.13.0
    networks:
      - web
    external_links:
      - nginx-proxy:travel-calculator.docker

  quality-assurance:
    build: docker/quality-assurance
    volumes:
      - .:/project

networks:
    web:

volumes:
  appdata: ~