parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Event\EventListener\AuthenticationListener:
        tags:
            - { name: kernel.event_listener, event: security.authentication.success }

    App\Event\EventListener\SwitchUserListener:
        tags:
            - { name: kernel.event_listener, event: security.switch_user }